domain: feliperibeiroo.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://feliperibeiroo.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /personal-page/      # place folder name if the site is served in a subfolder
